language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - travis_retry pip install -U pip wheel tox-travis
  - travis_retry pip install -U -r requirements.txt -e ".[test]"

script:
  - tox
